### ISSUE TITLE
Welcome on board

### ISSUE THREAD

**Issue by mesoylu** [mesoylu/swe574#1]
This is the first issue for our project. Lets write down random stuff below the issue, when everybody have written down some nonsense stuff underneath, the issue will be closed.

**Comment by mesoylu** [comment]
https://gfycat.com/dazzlingseriouselephant

**Comment by KayaOndul** [comment]
Hey

**Comment by burakkilicaslan** [comment]
Hello everyone

**Comment by OrkanMetin** [comment]
Hi there.

**Comment by mesoylu** [comment]
Since everybody responded, i will now close this issue. 

Issue is resolved with one gif and three salutations.
